name: Docker Publish (Beta Images)

on:
  workflow_dispatch:
  release:
    types: [prereleased]
jobs:
  get-latest-beta-release:
    runs-on: ubuntu-24.04
    outputs:
      release_tag: ${{ steps.beta-release.outputs.release_tag }}
    steps:        
      - name: Get Latest Beta Release
        id: beta-release
        env:
         GH_TOKEN: ${{ github.token }}
        run: |
          LATEST_BETA=$(gh release list --repo ${{ github.repository }} --limit 200 --json tagName,isPrerelease,isLatest,publishedAt | jq -r 'sort_by(.publishedAt) | reverse | map(select(.isPrerelease == true)) | first | .tagName')
          echo "release_tag=${LATEST_BETA}" >> $GITHUB_OUTPUT

  build-beta-images:
    needs: get-latest-beta-release
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    secrets: inherit
    with:
      release_type: 'beta'
      ref: ${{ needs.get-latest-beta-release.outputs.release_tag || github.ref }}