name: Docker Publish (Beta Images)

on:
  workflow_dispatch:
  release:
    types: [prereleased]
jobs:
  get-latest-beta-release:
    runs-on: ubuntu-24.04
    outputs:
      release_tag: ${{ steps.get_latest_beta.outputs.release_tag }}
    steps:
      - name: Get Latest Beta Release
        id: get_latest_beta
        run: |
          LATEST_BETA=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases | jq -r '[.[] | select(.prerelease == true)][0].tag_name')
          echo "release_tag=${LATEST_BETA}" >> $GITHUB_OUTPUT

  build-beta-images:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    secrets: inherit
    with:
      release_type: 'beta'
      ref: ${{ needs.get-latest-beta-release.outputs.release_tag }}
