name: Docker Publish (Production Images)

on:
  workflow_dispatch:
  release:
    types: [released]
  schedule:
    - cron: '0 4 * * 2'

jobs:
  get-latest-release:
    runs-on: ubuntu-24.04
    outputs:
      release_tag: ${{ steps.get_latest_release.outputs.release_tag }}
    steps:
      - name: Get Latest Release
        id: get_latest_release
        env:
         GH_TOKEN: ${{ github.token }}
        run: |
          LATEST_TAG=$(gh release list --repo ${{ github.repository }} --limit 200 --json tagName,isPrerelease,isLatest,publishedAt | jq -r '.[] | select(.isLatest == true) | .tagName')
          echo "release_tag=${LATEST_TAG}" >> $GITHUB_OUTPUT

  build-production-images:
    needs: get-latest-release
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    secrets: inherit
    with:
      release_type: 'latest'
      ref: ${{ needs.get-latest-release.outputs.release_tag }}